export const CONFIG = {
  source: {
    basePerCactus: 5,
    multiplier: 1,
  },
  tps: {
    maxTPS: 20,
    tpsDecayRate: 0.05,
  },
  world: {
    width: 4000,
    viewportWidth: 1200,
    farmingAreaStart: 200,
    farmingAreaEnd: 3800,
    blockSize: 120,
    layout: {
      groundHeight: 30,
      farmingHeight: 30,
      skyHeight: 40,
    },
  },
  inventory: {
    hotbarSize: 5,
    maxItems: 20,
  },
  items: {
    seeds: [{ id: "cactus_seed", name: "Cactus Seed", cost: 5, icon: "🌰" }],
    wands: [
      {
        id: "wooden_wand",
        name: "Wooden Wand",
        cost: 0,
        growthPower: 1,
        aoe: 0,
        icon: "🪄",
      },
      {
        id: "oak_wand",
        name: "Oak Wand",
        cost: 50,
        growthPower: 2,
        aoe: 1,
        icon: "✨",
      },
      {
        id: "silverwood_wand",
        name: "Silverwood Wand",
        cost: 200,
        growthPower: 4,
        aoe: 2,
        icon: "🔮",
      },
      {
        id: "thaumcraft_focus",
        name: "Thaumcraft Focus",
        cost: 500,
        growthPower: 6,
        aoe: 3,
        icon: "⚡",
      },
    ],
    hoes: [
      {
        id: "wooden_hoe",
        name: "Wooden Hoe",
        cost: 0,
        harvestPower: 1,
        aoe: 0,
        icon: "🔧",
      },
      {
        id: "iron_hoe",
        name: "Iron Hoe",
        cost: 75,
        harvestPower: 2,
        aoe: 1,
        icon: "⚒️",
      },
      {
        id: "mattock",
        name: "Mattock",
        cost: 300,
        harvestPower: 4,
        aoe: 2,
        icon: "🛠️",
      },
      {
        id: "kama",
        name: "Kama",
        cost: 800,
        harvestPower: 6,
        aoe: 3,
        icon: "⚔️",
      },
    ],
  },
  farmTypes: [
    {
      id: "vanilla_basic",
      name: "Basic Cactus Farm",
      cost: 100,
      description: "Simple vanilla Minecraft cactus farm",
      production: 1,
      minigame: "mod_approval",
      size: { width: 2, height: 1 },
      icon: "🏠",
    },
    {
      id: "vanilla_advanced",
      name: "Piston Cactus Farm",
      cost: 500,
      description: "Automated piston-based harvester",
      production: 5,
      minigame: "cactus_lottery",
      size: { width: 3, height: 1 },
      icon: "🏭",
    },
    {
      id: "mystical_agriculture",
      name: "Mystical Agriculture Plot",
      cost: 1000,
      description: "Magical essence-infused growing",
      production: 10,
      minigame: "count_cactus",
      size: { width: 3, height: 1 },
      icon: "🔯",
    },
    {
      id: "industrial_foregoing",
      name: "Plant Gatherer",
      cost: 2000,
      description: "High-tech automated harvesting",
      production: 20,
      minigame: "tech_calibration",
      size: { width: 4, height: 1 },
      icon: "⚙️",
    },
    {
      id: "stardew_greenhouse",
      name: "Stardew Greenhouse",
      cost: 3000,
      description: "Year-round magical growing",
      production: 30,
      minigame: "sprinkler_puzzle",
      size: { width: 5, height: 1 },
      icon: "🏛️",
    },
  ],
  players: [
    { name: "BlockMaster2024", avatar: "🧱" },
    { name: "RedstoneWizard", avatar: "⚡" },
    { name: "CactusSkeptic", avatar: "🤨" },
    { name: "BuildCrafter", avatar: "🔨" },
  ],
  mods: [
    { name: "Admin_Sarah", avatar: "👮‍♀️", personality: "strict" },
    { name: "Mod_Jackson", avatar: "🛡️", personality: "suspicious" },
  ],
};
